import type { FindItem } from "./item";

export const SNEAKER_GROUPS: FindItem["group"][] = [
  "jordan",
  "dunk",
  "newbalance",
  "adidas",
  "yeezy",
];

const NONE = { kind: "none" as const };

const LOOK =
  "Stop only if the pair is clean, the size tag is on, and the sole is not crushed. Sketchers, generics, no size, crushed soles, and obvious fakes are Pass.";

export const SNEAKERS: FindItem[] = [
  {
    id: "jordan-1",
    aisle: "sneakers",
    group: "jordan",
    groupLabel: "Jordan",
    name: "Air Jordan 1",
    badge: "Clean pair only",
    detail: "Jordan 1. Size tag on. Sole not crushed.",
    superColor: "Goodwill / thrift",
    lookFor: LOOK,
    aliases: ["jordan 1", "jordan1", "aj1", "air jordan 1", "jordan"],
    photo: "/photos/jordan-1.jpg",
    photoAlt: "Air Jordan 1 Banned colorway",
    shelf: 0,
    shelfLabel: "Type the tag in Cash",
    sale: NONE,
    note: "Pass unless a stored sold beats the tag after fees. No settled sale.",
  },
  {
    id: "jordan-3",
    aisle: "sneakers",
    group: "jordan",
    groupLabel: "Jordan",
    name: "Air Jordan 3",
    badge: "Clean pair only",
    detail: "Jordan 3. Size tag on. Sole not crushed.",
    superColor: "Goodwill / thrift",
    lookFor: LOOK,
    aliases: ["jordan 3", "jordan3", "aj3", "air jordan 3"],
    photo: "/photos/jordan-3.jpg",
    photoAlt: "Air Jordan 3 Retro",
    shelf: 0,
    shelfLabel: "Type the tag in Cash",
    sale: NONE,
    note: "Pass unless a stored sold beats the tag after fees. No settled sale.",
  },
  {
    id: "jordan-4",
    aisle: "sneakers",
    group: "jordan",
    groupLabel: "Jordan",
    name: "Air Jordan 4",
    badge: "Clean pair only",
    detail: "Jordan 4. Size tag on. Sole not crushed.",
    superColor: "Goodwill / thrift",
    lookFor: LOOK,
    aliases: ["jordan 4", "jordan4", "aj4", "air jordan 4"],
    photo: "/photos/jordan-4.jpg",
    photoAlt: "Air Jordan 4 Cement",
    photoNote: "Photo is a Jordan 4 Cement. Name the model Jordan 4 on the tag.",
    shelf: 0,
    shelfLabel: "Type the tag in Cash",
    sale: NONE,
    note: "Pass unless a stored sold beats the tag after fees. No settled sale.",
  },
  {
    id: "jordan-11",
    aisle: "sneakers",
    group: "jordan",
    groupLabel: "Jordan",
    name: "Air Jordan 11",
    badge: "Clean pair only",
    detail: "Jordan 11. Size tag on. Sole not crushed.",
    superColor: "Goodwill / thrift",
    lookFor: LOOK,
    aliases: ["jordan 11", "jordan11", "aj11", "air jordan 11", "xi"],
    photo: "/photos/jordan-11.jpg",
    photoAlt: "Air Jordan 11",
    shelf: 0,
    shelfLabel: "Type the tag in Cash",
    sale: NONE,
    note: "Pass unless a stored sold beats the tag after fees. No settled sale.",
  },
  {
    id: "dunk-sb",
    aisle: "sneakers",
    group: "dunk",
    groupLabel: "Nike Dunk SB",
    name: "Nike Dunk SB",
    badge: "Clean pair only",
    detail: "Dunk SB. Size tag on. Sole not crushed.",
    superColor: "Goodwill / thrift",
    lookFor: LOOK,
    aliases: ["dunk", "dunk sb", "nike dunk", "sb dunk", "nike sb"],
    photo: "/photos/dunk-sb.jpg",
    photoAlt: "Nike SB Dunk Low Pro",
    photoNote: "Photo is a Nike SB Dunk Low Pro. Name the model Dunk SB.",
    shelf: 0,
    shelfLabel: "Type the tag in Cash",
    sale: NONE,
    note: "Pass unless a stored sold beats the tag after fees. No settled sale.",
  },
  {
    id: "nb-990",
    aisle: "sneakers",
    group: "newbalance",
    groupLabel: "New Balance",
    name: "New Balance 990",
    badge: "Clean pair only",
    detail: "990. Size tag on. Sole not crushed.",
    superColor: "Goodwill / thrift",
    lookFor: LOOK,
    aliases: ["990", "nb 990", "new balance 990", "new balance"],
    photo: "/photos/nb-990.jpg",
    photoAlt: "New Balance 990 running shoe",
    shelf: 0,
    shelfLabel: "Type the tag in Cash",
    sale: NONE,
    note: "Pass unless a stored sold beats the tag after fees. No settled sale.",
  },
  {
    id: "nb-991",
    aisle: "sneakers",
    group: "newbalance",
    groupLabel: "New Balance",
    name: "New Balance 991",
    badge: "Clean pair only",
    detail: "991. Size tag on. Sole not crushed.",
    superColor: "Goodwill / thrift",
    lookFor: LOOK,
    aliases: ["991", "nb 991", "new balance 991"],
    photo: "/photos/nb-991.jpg",
    photoAlt: "New Balance 990 used as the 991 model photo",
    photoNote: "Photo is a New Balance 990. Name the model 991 on the tag.",
    shelf: 0,
    shelfLabel: "Type the tag in Cash",
    sale: NONE,
    note: "Pass unless a stored sold beats the tag after fees. No settled sale.",
  },
  {
    id: "nb-992",
    aisle: "sneakers",
    group: "newbalance",
    groupLabel: "New Balance",
    name: "New Balance 992",
    badge: "Clean pair only",
    detail: "992. Size tag on. Sole not crushed.",
    superColor: "Goodwill / thrift",
    lookFor: LOOK,
    aliases: ["992", "nb 992", "new balance 992"],
    photo: "/photos/nb-992.jpg",
    photoAlt: "New Balance 990 used as the 992 model photo",
    photoNote: "Photo is a New Balance 990. Name the model 992 on the tag.",
    shelf: 0,
    shelfLabel: "Type the tag in Cash",
    sale: NONE,
    note: "Pass unless a stored sold beats the tag after fees. No settled sale.",
  },
  {
    id: "nb-993",
    aisle: "sneakers",
    group: "newbalance",
    groupLabel: "New Balance",
    name: "New Balance 993",
    badge: "Clean pair only",
    detail: "993. Size tag on. Sole not crushed.",
    superColor: "Goodwill / thrift",
    lookFor: LOOK,
    aliases: ["993", "nb 993", "new balance 993"],
    photo: "/photos/nb-993.jpg",
    photoAlt: "New Balance 990 used as the 993 model photo",
    photoNote: "Photo is a New Balance 990. Name the model 993 on the tag.",
    shelf: 0,
    shelfLabel: "Type the tag in Cash",
    sale: NONE,
    note: "Pass unless a stored sold beats the tag after fees. No settled sale.",
  },
  {
    id: "nb-2002r",
    aisle: "sneakers",
    group: "newbalance",
    groupLabel: "New Balance",
    name: "New Balance 2002R",
    badge: "Clean pair only",
    detail: "2002R. Size tag on. Sole not crushed.",
    superColor: "Goodwill / thrift",
    lookFor: LOOK,
    aliases: ["2002r", "2002 r", "nb 2002", "new balance 2002r"],
    photo: "/photos/nb-2002r.jpg",
    photoAlt: "New Balance 2002R",
    shelf: 0,
    shelfLabel: "Type the tag in Cash",
    sale: NONE,
    note: "Pass unless a stored sold beats the tag after fees. No settled sale.",
  },
  {
    id: "nb-550",
    aisle: "sneakers",
    group: "newbalance",
    groupLabel: "New Balance",
    name: "New Balance 550",
    badge: "Clean pair only",
    detail: "550. Size tag on. Sole not crushed.",
    superColor: "Goodwill / thrift",
    lookFor: LOOK,
    aliases: ["550", "nb 550", "new balance 550"],
    photo: "/photos/nb-550.jpg",
    photoAlt: "New Balance 550",
    shelf: 0,
    shelfLabel: "Type the tag in Cash",
    sale: NONE,
    note: "Pass unless a stored sold beats the tag after fees. No settled sale.",
  },
  {
    id: "samba",
    aisle: "sneakers",
    group: "adidas",
    groupLabel: "Adidas",
    name: "Adidas Samba",
    badge: "Clean color only",
    detail: "Samba only if clean and the color is not destroyed.",
    superColor: "Goodwill / thrift",
    lookFor:
      "Samba only if the pair is clean and the color is not destroyed. Size tag on. Sole not crushed. Anything else is Pass.",
    aliases: ["samba", "adidas samba"],
    photo: "/photos/samba.jpg",
    photoAlt: "Adidas Samba OG",
    shelf: 0,
    shelfLabel: "Type the tag in Cash",
    sale: NONE,
    note: "Pass unless a stored sold beats the tag after fees. No settled sale.",
  },
  {
    id: "yeezy-350",
    aisle: "sneakers",
    group: "yeezy",
    groupLabel: "Yeezy",
    name: "Yeezy 350",
    badge: "Real boost only",
    detail: "350 only if the boost, insole, and size tag look real.",
    superColor: "Goodwill / thrift",
    lookFor:
      "Yeezy 350 only if the boost, insole, and size tag look real. Clean pair. Sole not crushed. Obvious fakes are Pass.",
    aliases: ["yeezy", "yeezy 350", "350 v2", "boost 350"],
    photo: "/photos/yeezy-350.jpg",
    photoAlt: "Adidas Yeezy Boost 350 V2 Sesame",
    photoNote: "Photo is a Yeezy 350 V2 Sesame. Name the model 350.",
    shelf: 0,
    shelfLabel: "Type the tag in Cash",
    sale: NONE,
    note: "Pass unless a stored sold beats the tag after fees. No settled sale.",
  },
  {
    id: "yeezy-700",
    aisle: "sneakers",
    group: "yeezy",
    groupLabel: "Yeezy",
    name: "Yeezy 700",
    badge: "Real boost only",
    detail: "700 only if the boost, insole, and size tag look real.",
    superColor: "Goodwill / thrift",
    lookFor:
      "Yeezy 700 only if the boost, insole, and size tag look real. Clean pair. Sole not crushed. Obvious fakes are Pass.",
    aliases: ["yeezy 700", "700 analog", "boost 700"],
    photo: "/photos/yeezy-700.jpg",
    photoAlt: "Yeezy Boost used as the 700 model photo",
    photoNote:
      "Photo is a Yeezy 350. Name the model 700. Look for the chunky 700 sole.",
    shelf: 0,
    shelfLabel: "Type the tag in Cash",
    sale: NONE,
    note: "Pass unless a stored sold beats the tag after fees. No settled sale.",
  },
];
