import type { FindItem } from "./item";

export const SPORT_GROUPS: FindItem["group"][] = [
  "football",
  "baseball",
  "basketball",
  "hockey",
  "soccer",
];

export const SPORTS: FindItem[] = [
  {
    id: "topps-fb",
    aisle: "sports",
    group: "football",
    groupLabel: "Football",
    sport: "Football",
    packType: "blaster",
    name: "2026 Topps Football blaster",
    badge: "Blaster",
    detail: "Retail blaster. Out Aug 21 2026.",
    superColor: "Blaster · hang tab / hook",
    lookFor:
      "Walmart or Target hook blaster. Not a hobby box. Shop asks about $25 to $40 are not sales.",
    aliases: [
      "2026 topps football",
      "topps football blaster",
      "topps flagship football",
      "flagship football",
      "topps football value",
    ],
    photo: "/photos/topps-fb.jpg",
    photoAlt: "2026 Topps Flagship Football retail value / blaster box",
    photoNote: "Photo is the 2026 Topps Football retail value box, the hook blaster format.",
    shelf: 25,
    shelfLabel: "Shop asks about $25 to $40",
    sale: { kind: "none" },
    note: "Leave it. No settled sale. Do not show $39.95 as a sale.",
  },
  {
    id: "optic-fb",
    aisle: "sports",
    group: "football",
    groupLabel: "Football",
    sport: "Football",
    packType: "blaster",
    name: "2025 Donruss Optic Football blaster",
    badge: "Blaster",
    detail: "Still on some Walmart hooks around $40.",
    superColor: "Blaster · Purple Shock on the pack",
    lookFor:
      "Walmart hook blaster. Look for Purple Shock Rated Rookie on the pack. Not a hobby box.",
    aliases: [
      "optic",
      "donruss optic",
      "optic football",
      "donruss optic blaster",
      "2025 optic",
      "purple shock",
    ],
    photo: "/photos/optic-fb.jpg",
    photoAlt: "2025 Panini Donruss Optic Football blaster box",
    shelf: 40,
    shelfLabel: "Printed about $40",
    sale: { kind: "none" },
    note: "Leave it at printed price. No settled sale stored.",
  },
  {
    id: "chrome-fb",
    aisle: "sports",
    group: "football",
    groupLabel: "Football",
    sport: "Football",
    packType: "hanger",
    name: "2025 Topps Chrome Football hanger",
    badge: "Hanger",
    detail: "Walmart hang tab about $49.90.",
    superColor: "Hanger · hang tab",
    lookFor:
      "Hang tab on a Walmart hook. 20 Chrome cards. Not a hobby box.",
    aliases: [
      "chrome football",
      "topps chrome football",
      "chrome hanger",
      "2025 chrome football",
    ],
    photo: "/photos/chrome-fb.jpg",
    photoAlt: "2025 Topps Chrome Football hanger box",
    shelf: 49.9,
    shelfLabel: "Walmart about $49.90",
    sale: { kind: "none" },
    note: "Leave it. No settled sale.",
  },
  {
    id: "select-fb",
    aisle: "sports",
    group: "football",
    groupLabel: "Football",
    sport: "Football",
    packType: "mega",
    name: "2025 Panini Select Football mega",
    badge: "Mega",
    detail: "Target mega about $51.99.",
    superColor: "Mega · Target hook",
    lookFor:
      "Target mega on a hook. Look for Black & Green Prizm Shock on this Target mega. Not a hobby box.",
    aliases: [
      "select football",
      "panini select",
      "select mega",
      "2025 select",
    ],
    photo: "/photos/select-fb.jpg",
    photoAlt: "2025 Panini Select Football Target mega box",
    shelf: 51.99,
    shelfLabel: "Target about $51.99",
    sale: { kind: "none" },
    note: "Leave it. No settled sale.",
  },
  {
    id: "topps-s1",
    aisle: "sports",
    group: "baseball",
    groupLabel: "Baseball",
    sport: "Baseball",
    packType: "value",
    name: "2026 Topps Series 1 Baseball value / blaster",
    badge: "Value / blaster",
    detail: "Printed often $24.99.",
    superColor: "Value / blaster · hang tab",
    lookFor:
      "Hang-tab value or blaster on a Walmart or Target hook. Spring Training parallels are in this retail format. Not a hobby box.",
    aliases: [
      "series 1",
      "topps series 1",
      "2026 series 1",
      "topps baseball",
      "series 1 blaster",
      "series 1 value",
    ],
    photo: "/photos/topps-s1.jpg",
    photoAlt: "2026 Topps Series 1 Baseball retail blaster box",
    photoNote: "Photo is the 2026 Topps Series 1 retail blaster, the hook value / blaster format.",
    shelf: 24.99,
    shelfLabel: "Printed often $24.99",
    sale: {
      kind: "settled",
      amount: 16.8,
      line: "Fanatics Collect Sep 7 2026 sold $16.80, $14.40, $14.40, $14.40, $13.20",
    },
    note: "Leave it. Sold under retail. After fees there is no cash left at printed price.",
  },
  {
    id: "wnba",
    aisle: "sports",
    group: "basketball",
    groupLabel: "Basketball",
    sport: "Basketball",
    packType: "hanger",
    name: "2025 Panini Prizm WNBA hanger",
    badge: "Hanger",
    detail: "Walmart hang tab about $21.87.",
    superColor: "Hanger · hang tab",
    lookFor:
      "Hang tab on a Walmart hook. Not a hobby box.",
    aliases: [
      "wnba",
      "prizm wnba",
      "wnba hanger",
      "2025 prizm wnba",
    ],
    photo: "/photos/wnba.jpg",
    photoAlt: "2025 Panini Prizm WNBA retail box",
    photoNote: "Photo is the 2025 Prizm WNBA retail box, not the exact Walmart hang tab.",
    shelf: 21.87,
    shelfLabel: "Walmart about $21.87",
    sale: { kind: "none" },
    note: "Leave it. No settled sale.",
  },
  {
    id: "bowman-bb",
    aisle: "sports",
    group: "basketball",
    groupLabel: "Basketball",
    sport: "Basketball",
    packType: "value",
    name: "2025-26 Bowman Basketball value box",
    badge: "Value",
    detail: "Walmart value box about $29.97.",
    superColor: "Value box · hang tab",
    lookFor:
      "Value box on a Walmart hook. 6 packs. Not a hobby box.",
    aliases: [
      "bowman basketball",
      "bowman value",
      "2025-26 bowman",
      "2026 bowman basketball",
    ],
    photo: "/photos/bowman-bb.jpg",
    photoAlt: "2025-26 Bowman Basketball value box",
    shelf: 29.97,
    shelfLabel: "Walmart about $29.97",
    sale: { kind: "none" },
    note: "Leave it. No settled sale.",
  },
  {
    id: "artifacts",
    aisle: "sports",
    group: "hockey",
    groupLabel: "Hockey",
    sport: "Hockey",
    packType: "blaster",
    name: "2026-27 Upper Deck Artifacts hockey blaster",
    badge: "Blaster",
    detail: "Not out until about Sept 23 2026.",
    superColor: "Blaster · hang tab",
    lookFor:
      "Hook blaster when it hits. Shop asks about $29.95 are not sales. Not a buy yet.",
    aliases: [
      "artifacts",
      "upper deck artifacts",
      "artifacts hockey",
      "2026-27 artifacts",
      "ud artifacts",
    ],
    photo: "/photos/artifacts.jpg",
    photoAlt: "2026-27 Upper Deck Artifacts hockey blaster box",
    shelf: 29.95,
    shelfLabel: "Shop asks about $29.95",
    sale: { kind: "none" },
    note: "Not a buy yet. No settled sale.",
  },
  {
    id: "fifa",
    aisle: "sports",
    group: "soccer",
    groupLabel: "Soccer",
    sport: "Soccer",
    packType: "blaster",
    name: "2026 Panini Prizm FIFA World Cup soccer blaster",
    badge: "Blaster",
    detail: "Printed about $34.95.",
    superColor: "Blaster · hang tab",
    lookFor:
      "Retail blaster on a Walmart or Target hook. Do not invent a World Cup premium. Leave it unless the shelf is under a stored sold after fees.",
    aliases: [
      "world cup",
      "fifa",
      "prizm world cup",
      "fifa blaster",
      "soccer blaster",
      "2026 prizm soccer",
    ],
    photo: "/photos/fifa.jpg",
    photoAlt: "2026 Panini Prizm FIFA World Cup soccer blaster box",
    shelf: 34.95,
    shelfLabel: "Printed about $34.95",
    sale: { kind: "none" },
    note: "Leave it. No settled sale. Do not invent a World Cup premium.",
  },
];
