import type { FindItem } from "./item";

export const STREET_GROUPS: FindItem["group"][] = [
  "supreme",
  "street",
  "collab",
];

const NONE = { kind: "none" as const };

const TAG =
  "Stop only if the tag is in and it is not an obvious fake. Random graphic tees, no tag, stained, and replica box logos are Pass.";

export const STREETWEAR: FindItem[] = [
  {
    id: "supreme",
    aisle: "streetwear",
    group: "supreme",
    groupLabel: "Supreme",
    name: "Supreme box logo or known collab",
    badge: "Tag in",
    detail: "Box logo or a known collab. Tag in. Not a replica.",
    superColor: "Streetwear",
    lookFor: TAG,
    aliases: [
      "supreme",
      "box logo",
      "supreme box logo",
      "supreme collab",
      "bogo",
    ],
    photo: "/photos/supreme.jpg",
    photoAlt: "Supreme box logo",
    photoNote: "Photo is the Supreme box logo. Look for that mark, tag in.",
    shelf: 0,
    shelfLabel: "Type the tag in Cash",
    sale: NONE,
    note: "No settled sale.",
  },
  {
    id: "bape",
    aisle: "streetwear",
    group: "street",
    groupLabel: "Bape, Palace, Stussy, Chrome Hearts",
    name: "Bape with tags",
    badge: "Tag in",
    detail: "Bape. Tag in. Not an obvious fake.",
    superColor: "Streetwear",
    lookFor: TAG,
    aliases: ["bape", "a bathing ape", "bathing ape"],
    photo: "/photos/bape.jpg",
    photoAlt: "BAPE storefront in Harajuku",
    photoNote: "Photo is a BAPE storefront. Name the model Bape on the tag.",
    shelf: 0,
    shelfLabel: "Type the tag in Cash",
    sale: NONE,
    note: "No settled sale.",
  },
  {
    id: "palace",
    aisle: "streetwear",
    group: "street",
    groupLabel: "Bape, Palace, Stussy, Chrome Hearts",
    name: "Palace with tags",
    badge: "Tag in",
    detail: "Palace. Tag in. Not an obvious fake.",
    superColor: "Streetwear",
    lookFor: TAG,
    aliases: ["palace", "palace skateboards"],
    photo: "/photos/palace.jpg",
    photoAlt: "Palace Skateboards logo",
    photoNote: "Photo is the Palace logo. Name the model Palace on the tag.",
    shelf: 0,
    shelfLabel: "Type the tag in Cash",
    sale: NONE,
    note: "No settled sale.",
  },
  {
    id: "stussy",
    aisle: "streetwear",
    group: "street",
    groupLabel: "Bape, Palace, Stussy, Chrome Hearts",
    name: "Stussy with tags",
    badge: "Tag in",
    detail: "Stussy. Tag in. Not an obvious fake.",
    superColor: "Streetwear",
    lookFor: TAG,
    aliases: ["stussy", "stüssy"],
    photo: "/photos/stussy.jpg",
    photoAlt: "Stussy storefront",
    photoNote: "Photo is a Stussy storefront. Name the model Stussy on the tag.",
    shelf: 0,
    shelfLabel: "Type the tag in Cash",
    sale: NONE,
    note: "No settled sale.",
  },
  {
    id: "chrome-hearts",
    aisle: "streetwear",
    group: "street",
    groupLabel: "Bape, Palace, Stussy, Chrome Hearts",
    name: "Chrome Hearts",
    badge: "Tag in",
    detail: "Chrome Hearts. Tag in. Not an obvious fake.",
    superColor: "Streetwear",
    lookFor: TAG,
    aliases: ["chrome hearts", "chrome heart"],
    photo: "/photos/chrome-hearts.jpg",
    photoAlt: "Chrome Hearts bracelet",
    photoNote: "Photo is a Chrome Hearts bracelet. Name Chrome Hearts on the tag.",
    shelf: 0,
    shelfLabel: "Type the tag in Cash",
    sale: NONE,
    note: "No settled sale.",
  },
  {
    id: "off-white",
    aisle: "streetwear",
    group: "collab",
    groupLabel: "Nike or Adidas collab",
    name: "Off-White collab with tags",
    badge: "Tag in",
    detail: "Nike or Adidas collab. Off-White. Tag in.",
    superColor: "Streetwear",
    lookFor:
      "Nike or Adidas collab only with tags. Off-White or Ambush. Random Nike tees are Pass.",
    aliases: ["off-white", "off white", "offwhite", "nike collab"],
    photo: "/photos/offwhite.jpg",
    photoAlt: "Off-White x Nike Air Force 1 MCA",
    photoNote:
      "Photo is an Off-White x Nike Air Force 1. Name the Off-White collab on the tag.",
    shelf: 0,
    shelfLabel: "Type the tag in Cash",
    sale: NONE,
    note: "No settled sale.",
  },
  {
    id: "ambush",
    aisle: "streetwear",
    group: "collab",
    groupLabel: "Nike or Adidas collab",
    name: "Ambush collab with tags",
    badge: "Tag in",
    detail: "Nike or Adidas collab. Ambush. Tag in.",
    superColor: "Streetwear",
    lookFor:
      "Nike or Adidas collab only with tags. Off-White or Ambush. Random Adidas tees are Pass.",
    aliases: ["ambush", "adidas collab", "ambush nike"],
    photo: "/photos/ambush.jpg",
    photoAlt: "AMBUSH x Nike Air Max 180 High",
    photoNote:
      "Photo is an Ambush x Nike Air Max 180. Name the Ambush collab on the tag.",
    shelf: 0,
    shelfLabel: "Type the tag in Cash",
    sale: NONE,
    note: "No settled sale.",
  },
];
