import type { FindItem } from "./item";

export const TECH_GROUPS: FindItem["group"][] = ["apple", "electronics"];

const NONE = { kind: "none" as const };

export const TECH: FindItem[] = [
  {
    id: "iphone",
    aisle: "tech",
    group: "apple",
    groupLabel: "Apple / gaming",
    name: "iPhone 12 or newer",
    badge: "Powers on · not iCloud locked",
    detail: "iPhone 12 or newer. Powers on. Not iCloud locked.",
    superColor: "Tech",
    lookFor:
      "Powers on. Not iCloud locked. Cracked no-power phones and locked iPhones are Pass.",
    aliases: [
      "iphone",
      "iphone 12",
      "iphone 13",
      "iphone 14",
      "iphone 15",
      "iphone 16",
      "tech",
    ],
    photo: "/photos/iphone.jpg",
    photoAlt: "iPhone 12",
    photoNote: "Photo is an iPhone 12. Name the model on the Settings screen.",
    shelf: 0,
    shelfLabel: "Type the tag in Cash",
    sale: NONE,
    note: "No settled sale. Do not invent an iPhone sold number.",
  },
  {
    id: "ipad",
    aisle: "tech",
    group: "apple",
    groupLabel: "Apple / gaming",
    name: "iPad 8th gen or newer",
    badge: "Powers on",
    detail: "iPad 8th gen or newer, or a recent Air / Pro. Powers on.",
    superColor: "Tech",
    lookFor: "Powers on. Recent Air or Pro is on this list. Older iPads are Pass.",
    aliases: [
      "ipad",
      "ipad air",
      "ipad pro",
      "ipad 8",
      "8th gen",
      "ipad 9",
      "ipad 10",
    ],
    photo: "/photos/ipad.jpg",
    photoAlt: "iPad Air",
    photoNote: "Photo is an iPad Air. Name the model iPad 8th gen, Air, or Pro.",
    shelf: 0,
    shelfLabel: "Type the tag in Cash",
    sale: NONE,
    note: "No settled sale.",
  },
  {
    id: "macbook",
    aisle: "tech",
    group: "apple",
    groupLabel: "Apple / gaming",
    name: "MacBook 2018 or newer",
    badge: "Boots",
    detail: "MacBook 2018 or newer that boots.",
    superColor: "Tech",
    lookFor: "It has to boot. 2017 and older are Pass.",
    aliases: [
      "macbook",
      "macbook pro",
      "macbook air",
      "macbook 2018",
      "m1 macbook",
    ],
    photo: "/photos/macbook.jpg",
    photoAlt: "MacBook Pro 16 M1 Pro 2021",
    photoNote: "Photo is a 2021 MacBook Pro 16. Name the model MacBook 2018 or newer.",
    shelf: 0,
    shelfLabel: "Type the tag in Cash",
    sale: NONE,
    note: "No settled sale.",
  },
  {
    id: "airpods",
    aisle: "tech",
    group: "apple",
    groupLabel: "Apple / gaming",
    name: "AirPods Pro or Max",
    badge: "Pairs",
    detail: "AirPods Pro or Max that pair.",
    superColor: "Tech",
    lookFor: "They have to pair. Plain AirPods and dead cases are Pass.",
    aliases: [
      "airpods",
      "airpods pro",
      "airpods max",
      "air pod",
      "airpods pro max",
    ],
    photo: "/photos/airpods.jpg",
    photoAlt: "AirPods Pro 2nd generation",
    photoNote: "Photo is AirPods Pro. Name AirPods Pro or Max.",
    shelf: 0,
    shelfLabel: "Type the tag in Cash",
    sale: NONE,
    note: "No settled sale.",
  },
  {
    id: "watch",
    aisle: "tech",
    group: "apple",
    groupLabel: "Apple / gaming",
    name: "Apple Watch Series 6 or newer",
    badge: "Pairs",
    detail: "Series 6 or newer that pairs.",
    superColor: "Tech",
    lookFor: "It has to pair. Series 5 and older are Pass.",
    aliases: [
      "apple watch",
      "watch series 6",
      "watch series 7",
      "watch series 8",
      "watch series 9",
      "watch ultra",
    ],
    photo: "/photos/watch.jpg",
    photoAlt: "Apple Watch Series 8",
    photoNote: "Photo is an Apple Watch Series 8. Name Series 6 or newer.",
    shelf: 0,
    shelfLabel: "Type the tag in Cash",
    sale: NONE,
    note: "No settled sale.",
  },
  {
    id: "switch",
    aisle: "tech",
    group: "apple",
    groupLabel: "Apple / gaming",
    name: "Nintendo Switch or OLED",
    badge: "Powers on",
    detail: "Switch or OLED that powers on.",
    superColor: "Tech",
    lookFor: "Powers on. Dead docks and no-power units are Pass.",
    aliases: [
      "switch",
      "nintendo switch",
      "switch oled",
      "nintendo oled",
    ],
    photo: "/photos/switch.jpg",
    photoAlt: "Nintendo Switch docked with Joy-Con",
    shelf: 0,
    shelfLabel: "Type the tag in Cash",
    sale: NONE,
    note: "No settled sale.",
  },
  {
    id: "sony-bose",
    aisle: "tech",
    group: "electronics",
    groupLabel: "Other electronics worth a look",
    name: "Sony or Bose headphones",
    badge: "Powers on",
    detail: "Recent Sony or Bose headphones that power on.",
    superColor: "Tech",
    lookFor:
      "Recent Sony or Bose that power on. Still Pass without a stored sold. Mystery earbuds are Pass.",
    aliases: [
      "sony headphones",
      "bose",
      "quietcomfort",
      "wh-1000",
      "wh1000",
      "sony bose",
      "bose headphones",
      "electronics",
      "headphones",
    ],
    photo: "/photos/bose.jpg",
    photoAlt: "Bose QuietComfort 35 II wireless headphones",
    photoNote:
      "Photo is Bose QuietComfort 35 II. Name recent Sony or Bose headphones.",
    shelf: 0,
    shelfLabel: "Type the tag in Cash",
    sale: NONE,
    note: "No settled sale.",
  },
  {
    id: "camera",
    aisle: "tech",
    group: "electronics",
    groupLabel: "Other electronics worth a look",
    name: "Mirrorless or recent point-and-shoot",
    badge: "Powers on",
    detail: "A mirrorless or recent point-and-shoot that powers on.",
    superColor: "Tech",
    lookFor:
      "Powers on. Still Pass without a stored sold. DVD players and unknown bodies are Pass.",
    aliases: [
      "camera",
      "mirrorless",
      "sony alpha",
      "point and shoot",
      "point-and-shoot",
      "electronics",
    ],
    photo: "/photos/camera.jpg",
    photoAlt: "Sony Alpha 7R IV mirrorless camera",
    photoNote: "Photo is a Sony Alpha 7R IV. Name the camera model on the body.",
    shelf: 0,
    shelfLabel: "Type the tag in Cash",
    sale: NONE,
    note: "No settled sale.",
  },
];
